### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adrianocr** [massamino/klipper-config#1]
Hi what's the license situation with your modded files? I'm interested in pulling this repo, merging your nozzle_prime fix into the original dudeofawesome/klipper-config repo, and submitting a pull request so dudeofawesome can merge it into the master branch. Cool with you?

**Comment by massamino** [comment]
Hi,

Easy. Free to use and I'm not responsible when your printer is on fire. 😁

Kind regards.

**Comment by massamino** [comment]
I created an MIT license to make it more clear. Thanks for asking.
